name: verstobbertje
description: Een demonstratie van een locatiegebaseerd verstopspel.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.5.3
  geolocator: ^13.0.4
  flutter_map: ^8.3.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/stobbekarakter.png
    - assets/images/stobbekarakter_welkom.webp
    - assets/images/players/
