import 'package:flutter/material.dart';
import '../app_state.dart';
import 'widgets.dart';

class ActiveGameScreen extends StatelessWidget {
  const ActiveGameScreen({required this.state, super.key}); final AppState state;
  @override Widget build(BuildContext context) => ListenableBuilder(listenable: state, builder: (context, _) => Scaffold(appBar: AppBar(title: const Text('Game X'), actions: const [Padding(padding: EdgeInsets.all(12), child: DemoBadge())]), body: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 760), child: ListView(padding: const EdgeInsets.all(20), children: [
    Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [const Chip(avatar: Icon(Icons.person_search), label: Text('ROL: ZOEKER')), Chip(avatar: const Icon(Icons.circle, size: 12), label: Text(state.gameFinished ? 'AFGEROND' : 'SPEL ACTIEF'))]),
    const SizedBox(height: 12), Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: const Color(0xff223f31), borderRadius: BorderRadius.circular(24)), child: Column(children: [const Text('RESTERENDE TIJD', style: TextStyle(color: Colors.white70, fontWeight: FontWeight.w700)), const SizedBox(height: 12), const Row(children: [_Time('00','dagen'),_Time('00','uren'),_Time('26','minuten'),_Time('30','seconden')]), const Divider(color: Colors.white24, height: 28), Text('${state.activeGame.playersFound} van de ${state.activeGame.totalPlayers} gevonden', style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w900, fontSize: 20)), const SizedBox(height: 8), LinearProgressIndicator(value: state.activeGame.playersFound/state.activeGame.totalPlayers, minHeight: 9, borderRadius: BorderRadius.circular(8))])),
    const SectionTitle('Zoekgebied'), const MapPlaceholder(),
    const SectionTitle('Jouw acties'), Wrap(spacing: 10, runSpacing: 10, children: [ActionChip(avatar: const Icon(Icons.visibility), label: const Text('2 zichtbare verstoppers'), onPressed: (){}), ActionChip(avatar: const Icon(Icons.lightbulb), label: const Text('Koop hint (demo)'), onPressed: () => _notice(context,'Hint ontgrendeld: kijk bij de grote eik. Geen echte betaling.')), ActionChip(avatar: const Icon(Icons.quiz), label: const Text('Beantwoord vraag'), onPressed: () => _notice(context,'Goed! Amsterdam is de hoofdstad van Nederland.'))]),
    const SizedBox(height: 18), FilledButton.icon(onPressed: state.gameFinished ? null : () => _proximity(context), icon: const Icon(Icons.sensors), label: const Text('Simuleer speler binnen 5 meter')), const SizedBox(height: 10), OutlinedButton.icon(onPressed: state.gameFinished ? null : () => _hiderWarning(context), icon: const Icon(Icons.visibility_off), label: const Text('Bekijk hider-scenario')), TextButton(onPressed: () => _hiderResult(context), child: const Text('Bekijk hider-resultaat')), const SizedBox(height: 10), TextButton(onPressed: state.gameFinished ? () => _result(context) : () => _finish(context), child: Text(state.gameFinished ? 'Bekijk zoeker-resultaat' : 'Beëindig demo-spel')),
  ])))));

  static void _notice(BuildContext context,String text)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(text)));
  void _proximity(BuildContext context)=>showDialog<void>(context:context,builder:(dialogContext)=>AlertDialog(icon:const Icon(Icons.radar,size:42),title:const Text('Speler dichtbij!'),content:const Text('Er is een speler binnen 5 meter.'),actions:[TextButton(onPressed:()=>Navigator.pop(dialogContext),child:const Text('Later')),FilledButton(onPressed:(){Navigator.pop(dialogContext);state.foundPlayer();showDialog<void>(context:context,builder:(c)=>AlertDialog(icon:const Icon(Icons.celebration,size:46),title:const Text('Gevonden!'),content:const Text('Je hebt speler XYZ uitgeschakeld.\nGoed gedaan!'),actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Verder zoeken'))]));},child:const Text('GEVONDEN'))]));
  void _hiderWarning(BuildContext context)=>showDialog<void>(context:context,builder:(c)=>AlertDialog(icon:const Icon(Icons.warning_amber,size:44),title:const Text('Let op!'),content:Text('Zoeker Arie zit binnen 5 meter van jou.\n\n${state.activeGame.invisibilityAvailable?'Je onzichtbaarheidskracht is nog beschikbaar.':'Je onzichtbaarheidskracht is al gebruikt.'}'),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Sluiten')),FilledButton(onPressed:state.activeGame.invisibilityAvailable?(){state.useInvisibility();Navigator.pop(c);_notice(context,'Je bent tijdelijk onzichtbaar (simulatie).');}:null,child:const Text('Onzichtbaar maken'))]));
  void _finish(BuildContext context){state.finishGame();_result(context);}
  void _hiderResult(BuildContext context)=>showModalBottomSheet<void>(context:context,builder:(c)=>Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.sentiment_dissatisfied,size:58),const Text('Helaas, je bent gevonden!',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900),textAlign:TextAlign.center),const SizedBox(height:10),const Text('Overlevingstijd: 1 uur en 42 minuten'),const Text('Ontvangen: 420 punten'),const Text('Rank: Beginner • 54% naar Avonturier'),const SizedBox(height:16),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Sluiten'))])));
  void _result(BuildContext context)=>showModalBottomSheet<void>(context:context,isScrollControlled:true,builder:(c)=>Padding(padding:EdgeInsets.fromLTRB(24,24,24,MediaQuery.viewInsetsOf(c).bottom+32),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.emoji_events,color:Color(0xffd99d18),size:64),const Text('Sterk gezocht, Arie!',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),Text('${state.activeGame.playersFound} spelers gevonden • 840 punten'),const Text('Rank: Beginner • 68% naar Avonturier'),const SizedBox(height:12),const Card(child:ListTile(leading:Icon(Icons.account_balance_wallet_outlined),title:Text('Demoresultaat: € 4,50'),subtitle:Text('Mockbedrag — er is geen geld ontvangen of overgemaakt.'))),const SizedBox(height:12),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Terug naar het spel'))]));
}
class _Time extends StatelessWidget { const _Time(this.value,this.label); final String value,label; @override Widget build(BuildContext context)=>Expanded(child:Column(children:[Text(value,style:const TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.w900)),Text(label,style:const TextStyle(color:Colors.white60,fontSize:11))])); }
