import 'package:flutter/material.dart';
import '../app_state.dart';
import '../data/mock_game_repository.dart';
import '../domain/models.dart';
import '../services/financial_service.dart';
import 'widgets.dart';

class CreateGameScreen extends StatefulWidget { const CreateGameScreen({required this.state,super.key}); final AppState state; @override State<CreateGameScreen> createState()=>_CreateGameScreenState(); }
class _CreateGameScreenState extends State<CreateGameScreen>{
  int step=0; final name=TextEditingController(text:'Test123'); final intro=TextEditingController(); bool isPublic=true,hints=true,questions=true; double entry=10; int players=10,duration=120; StartCondition condition=StartCondition.participantCount;
  @override void dispose(){name.dispose();intro.dispose();super.dispose();}
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Nieuw spel')),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:760),child:Stepper(currentStep:step,onStepTapped:(i)=>setState(()=>step=i),onStepContinue:step==3?_publish:()=>setState(()=>step++),onStepCancel:step==0?null:()=>setState(()=>step--),controlsBuilder:(context,d)=>Padding(padding:const EdgeInsets.only(top:20),child:Row(children:[Expanded(child:FilledButton(onPressed:d.onStepContinue,child:Text(step==3?'Stel spel beschikbaar':'Volgende'))),if(step>0)...[const SizedBox(width:8),TextButton(onPressed:d.onStepCancel,child:const Text('Terug'))]])),steps:[
    Step(title:const Text('Basis'),isActive:step>=0,content:Column(children:[TextField(controller:name,decoration:const InputDecoration(labelText:'Naam van het spel')),const SizedBox(height:12),SwitchListTile(contentPadding:EdgeInsets.zero,title:Text(isPublic?'Openbaar spel':'Privéspel'),subtitle:const Text('Wie kan dit spel ontdekken?'),value:isPublic,onChanged:(v)=>setState(()=>isPublic=v)),_Slider(label:'Duur',value:duration.toDouble(),min:30,max:360,divisions:11,suffix:' minuten',onChanged:(v)=>setState(()=>duration=v.round())),_Slider(label:'Demo-inleg',value:entry,min:0,max:25,divisions:25,suffix:' euro',onChanged:(v)=>setState(()=>entry=v)),_Slider(label:'Maximum deelnemers',value:players.toDouble(),min:6,max:60,divisions:9,suffix:' spelers',onChanged:(v)=>setState(()=>players=v.round())),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Hints kunnen worden gekocht'),value:hints,onChanged:(v)=>setState(()=>hints=v)),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Vragen kunnen worden beantwoord'),value:questions,onChanged:(v)=>setState(()=>questions=v))])),
    Step(title:const Text('Zoekgebied'),isActive:step>=1,content:const Column(children:[_AreaRow('Land','Nederland'),_AreaRow('Provincie','Flevoland'),_AreaRow('Stad','Almere'),_AreaRow('Wijk','Alle'),_AreaRow('Specifiek gebied','Niet van toepassing'),SizedBox(height:12),MapPlaceholder(height:190),Padding(padding:EdgeInsets.all(8),child:Text('Later vervangbaar door een echte kaartservice.',style:TextStyle(fontSize:12)))])),
    Step(title:const Text('Start & introductie'),isActive:step>=2,content:Column(children:[RadioListTile(value:StartCondition.participantCount,groupValue:condition,onChanged:(v)=>setState(()=>condition=v!),title:const Text('Start bij genoeg deelnemers'),subtitle:Text('Wanneer $players spelers meedoen')),RadioListTile(value:StartCondition.scheduled,groupValue:condition,onChanged:(v)=>setState(()=>condition=v!),title:const Text('Start op datum en tijd'),subtitle:const Text('25 augustus 2026 om 16:00')),TextField(controller:intro,maxLines:5,decoration:const InputDecoration(labelText:'Spelintroductie',hintText:'Vertel spelers wat ze kunnen verwachten…')),const SizedBox(height:10),OutlinedButton.icon(onPressed:()=>setState(()=>intro.text='Durf jij je te verstoppen in Almere? Slimme zoekers, verrassende hints en een spannend zoekgebied wachten op je. Blijf uit zicht en speel voor de eer!'),icon:const Icon(Icons.auto_awesome),label:const Text('Genereer introductie met AI'))])),
    Step(title:const Text('Controleren'),isActive:step>=3,content:_Review(name:name.text,isPublic:isPublic,duration:duration,entry:entry,players:players,hints:hints,questions:questions,intro:intro.text)),
  ])))) ;
  void _publish(){final now=DateTime.now();widget.state.publish(Game(id:'created-${now.millisecondsSinceEpoch}',name:name.text.trim().isEmpty?'Naamloos spel':name.text.trim(),organizer:'Arie',description:intro.text.trim().isEmpty?'Een nieuw avontuur in Almere.':intro.text.trim(),area:demoArea,status:GameStatus.available,start:DateTime(2026,8,25,16),duration:Duration(minutes:duration),entryFee:entry,participants:1,maxParticipants:players,distanceKm:1.2,isPublic:isPublic,rules:GameRules(hintsEnabled:hints,questionsEnabled:questions)));showDialog<void>(context:context,builder:(c)=>AlertDialog(icon:const Icon(Icons.rocket_launch,size:46),title:const Text('Spel is beschikbaar!'),content:Text('${name.text} staat nu lokaal tussen Beschikbare spellen.'),actions:[FilledButton(onPressed:(){Navigator.pop(c);Navigator.pop(context);},child:const Text('Klaar'))]));}
}
class _Slider extends StatelessWidget{const _Slider({required this.label,required this.value,required this.min,required this.max,required this.divisions,required this.suffix,required this.onChanged});final String label,suffix;final double value,min,max;final int divisions;final ValueChanged<double> onChanged;@override Widget build(BuildContext context)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('$label: ${value.round()}$suffix',style:const TextStyle(fontWeight:FontWeight.w700)),Slider(value:value,min:min,max:max,divisions:divisions,onChanged:onChanged)]);}
class _AreaRow extends StatelessWidget{const _AreaRow(this.label,this.value);final String label,value;@override Widget build(BuildContext context)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.location_on_outlined),title:Text(label),trailing:Text(value,style:const TextStyle(fontWeight:FontWeight.w700)));}
class _Review extends StatelessWidget{const _Review({required this.name,required this.isPublic,required this.duration,required this.entry,required this.players,required this.hints,required this.questions,required this.intro});final String name,intro;final bool isPublic,hints,questions;final int duration,players;final double entry;@override Widget build(BuildContext context){final money=const FinancialService().calculate(players:players,entryFee:entry);return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),Text(isPublic?'Openbaar':'Privé'),const Divider(),_AreaRow('Duur','$duration minuten'),_AreaRow('Deelnemers','maximaal $players'),_AreaRow('Mechanieken','${hints?'Hints':''}${hints&&questions?' • ':''}${questions?'Vragen':''}'),const SizedBox(height:10),Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Gesimuleerde prijzenpot',style:TextStyle(fontWeight:FontWeight.w800)),Text('$players × € ${entry.toStringAsFixed(2)} = € ${money.grossPool.toStringAsFixed(2)} bruto'),Text('Voorbeeld platformkosten: € ${money.platformFee.toStringAsFixed(2)}'),Text('Getoonde prijzenpot: € ${money.prizePool.toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.w800)),const Text('Demo — geen echt geld',style:TextStyle(fontSize:12))]))),if(intro.isNotEmpty)...[const SizedBox(height:12),Text(intro)]]);}}
