-- Shared game metadata required by the public game API.
ALTER TABLE games ADD COLUMN name TEXT NOT NULL DEFAULT 'Naamloos spel';
ALTER TABLE games ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN country TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN province TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN city TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN neighbourhood TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN specific_area TEXT NOT NULL DEFAULT '';
ALTER TABLE games ADD COLUMN duration_minutes INTEGER NOT NULL DEFAULT 120;
ALTER TABLE games ADD COLUMN max_participants INTEGER NOT NULL DEFAULT 24;
ALTER TABLE games ADD COLUMN distance_km REAL NOT NULL DEFAULT 0;
ALTER TABLE games ADD COLUMN start_condition TEXT NOT NULL DEFAULT 'scheduled';
ALTER TABLE games ADD COLUMN participant_threshold INTEGER;
ALTER TABLE games ADD COLUMN is_public INTEGER NOT NULL DEFAULT 1;
ALTER TABLE games ADD COLUMN hints_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE games ADD COLUMN questions_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE games ADD COLUMN game_type TEXT NOT NULL DEFAULT 'classic';
ALTER TABLE games ADD COLUMN allow_rejoin_after_found INTEGER NOT NULL DEFAULT 0;
